test_debug_build:
  image: greenaddress/android@sha256:d59365ad8d61059e915d233a6afcbcb69be6320f0f62f2cb75d2730fe1e6819f
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - pushd app && ./prepare_fdroid.sh && popd
    - ./gradlew --project-dir=bitcoinj/tools build
    - ./gradlew assembleProductionDebug assembleBtctestnetDebug assemblePublicregtestDebug

build_tag_release:
  image: greenaddress/android@sha256:d59365ad8d61059e915d233a6afcbcb69be6320f0f62f2cb75d2730fe1e6819f
  artifacts:
    name: "greenbits-release-$CI_COMMIT_REF_NAME"
    when: on_success
    paths:
    - app/build/outputs/apk/*.apk
    - app/build/outputs/mapping/*/release/mapping.txt
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - pushd app && ./prepare_fdroid.sh && popd
    - ./gradlew assembleProductionRelease assembleBtctestnetRelease assembleProduction_21Release assembleBtctestnet_21Release
  only:
    - tags

test_debug_osx_build:
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - pushd app && ./prepare_fdroid.sh && popd
    - ./gradlew --project-dir=bitcoinj/tools build
    - ./gradlew assembleProductionDebug assembleBtctestnetDebug assemblePublicregtestDebug

build_tag_osx_release:
  tags:
    - osx
  artifacts:
    name: "greenbits-release-$CI_COMMIT_REF_NAME"
    when: on_success
    paths:
    - app/build/outputs/apk/*.apk
    - app/build/outputs/mapping/*/release/mapping.txt
  script:
    - cd $CI_PROJECT_DIR
    - pushd app && ./prepare_fdroid.sh && popd
    - ./gradlew assembleProductionRelease assembleBtctestnetRelease assembleProduction_21Release assembleBtctestnet_21Release
  only:
    - tags
