build_tag_release:
  image: greenaddress/android@sha256:62e0e91850b79efa524733c4f7856f0631441bd2b9e59b59329f2da94a007dcc
  script:
    - cd $CI_PROJECT_DIR
    - ./app/fetch_libwally_binaries.sh
    - ./gradlew lintProductionRelease
    - ./gradlew assembleProductionRelease
