build_tag_release:
  image: greenaddress/android@sha256:979d4491884a2eb7c42beed2918c0ea6a413616a27fae48634f46322e08dfb06
  script:
    - cd $CI_PROJECT_DIR
    - ./app/fetch_libwally_binaries.sh
    - ./gradlew lintProductionRelease
    - ./gradlew assembleProductionRelease
