language: generic
sudo: required

services:
  - docker

before_install:
  - docker pull greenaddress/android

env:
  - NETWORK=Production BUILD=Debug
  - NETWORK=Production BUILD=Release
  - NETWORK=Btctestnet BUILD=Debug
  - NETWORK=Btctestnet BUILD=Release
  - NETWORK=Publicregtest BUILD=Debug
  - NETWORK=Publicregtest BUILD=Release
  - NETWORK=Elementsregtest BUILD=Debug
  - NETWORK=Elementsregtest BUILD=Release  

git:
    submodules: false

script: docker run -v $PWD:/gb greenaddress/android /bin/sh -c "cd /gb/app && ./prepare_fdroid.sh && cd /gb && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew assemble$NETWORK$BUILD"
